property:
  server-url: http://localhost:9090
#  server-url: http://47.113.109.9:9090
  img-url: http://47.113.109.9:88/vms/

spring:
  resources:
    static-locations: classpath:/static,classpath:/templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///vms?useUnicode=true&chararcterEncoding=utf-8
#    url: jdbc:mysql://172.18.253.191:3306/vms?useUnicode=true&chararcterEncoding=utf-8
    username: root
    password: root
#    password: Lmcaly1132
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.vms.bean
  mapper-locations: classpath:com/vms/dao/**/mapping/*.xml
  configuration:
    # 打印sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 下划线转驼峰配置
    map-underscore-to-camel-case: true

fdfs:
  so-timeout: 15010
  connect-timeout: 6010
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 172.18.253.191:22122
#    - 47.113.109.9:22122

server:
  port: 9090
